<a href="https://colab.research.google.com/github/lavanyalaguduva/learn_nn/blob/main/coding_nn_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Coding Neurons and layers**

**Coding a neuron**





In [ ]:
inputs = [1,2,3]
weights = [0.3,2.0,0.8]
bias = 2.2

outputs = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(outputs)

8.9


**Coding a layer**

In [ ]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

weights1=weights[0]
weights2=weights[1]
weights3=weights[2]

bias = [2, 3, 0.5]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
 # Neuron 1:
 inputs[0]*weights1[0] +
 inputs[1]*weights1[1] +
 inputs[2]*weights1[2] +
 inputs[3]*weights1[3] + bias1,
 # Neuron 2:
 inputs[0]*weights2[0] +
 inputs[1]*weights2[1] +
 inputs[2]*weights2[2] +
 inputs[3]*weights2[3] + bias2,
 # Neuron 3:
 inputs[0]*weights3[0] +
 inputs[1]*weights3[1] +
 inputs[2]*weights3[2] +
 inputs[3]*weights3[3] + bias3]

print(outputs)


[4.8, 1.21, 2.385]


**Using Loops to code a layer**

In [ ]:
inputs = [1, 2, 3, 2.5]

##LIST OF WEIGHTS
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

##LIST OF BIASES
bias = [2, 3, 0.5]

layer_outputs = []

for neuron_weight, neuron_bias in zip(weights, bias):
  print(f'Neuron Weight: {neuron_weight}')
  print(f'Neuron Bias: {neuron_bias}')
  print(f'Inputs: {inputs}')
  neuron_output = 0
  for input,weight in zip(inputs, neuron_weight):
    neuron_output += input*weight
    print(f'Neuron Output: {neuron_output}')
  neuron_output += neuron_bias
  print(f'Neuron Output After Bias: {neuron_output}')
  layer_outputs.append(neuron_output)
print(f'Layer Outputs: {layer_outputs}')



Neuron Weight: [0.2, 0.8, -0.5, 1]
Neuron Bias: 2
Inputs: [1, 2, 3, 2.5]
Neuron Output: 0.2
Neuron Output: 1.8
Neuron Output: 0.30000000000000004
Neuron Output: 2.8
Neuron Output After Bias: 4.8
Neuron Weight: [0.5, -0.91, 0.26, -0.5]
Neuron Bias: 3
Inputs: [1, 2, 3, 2.5]
Neuron Output: 0.5
Neuron Output: -1.32
Neuron Output: -0.54
Neuron Output: -1.79
Neuron Output After Bias: 1.21
Neuron Weight: [-0.26, -0.27, 0.17, 0.87]
Neuron Bias: 0.5
Inputs: [1, 2, 3, 2.5]
Neuron Output: -0.26
Neuron Output: -0.8
Neuron Output: -0.29000000000000004
Neuron Output: 1.8849999999999998
Neuron Output After Bias: 2.385
Layer Outputs: [4.8, 1.21, 2.385]


**Using Numpy**

Single Neuron

In [ ]:
import numpy as np
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1]
bias = 2
inputs_array = np.array(inputs)
weights_array = np.array(weights)
output = np.dot(inputs_array, weights_array) + bias
print(output)


4.8


Single Layer

In [45]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# Convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)

print(f'Input: {inputs_array}')
print(f'Input array shape: {inputs_array.shape}')
weights_array = np.array(weights)
print(f'Weights: {weights_array}')
print(f'Weight array shape: {weights_array.shape}')
biases_array = np.array(biases)
output = np.dot(weights_array,inputs_array)
print(f'Output array before bias: {output}')
print(f'Output array before bias shape: {output.shape}')
print(f'Biases: {biases_array}')
print(f'Biases array shape: {biases_array.shape}')
output = output+biases_array
print(output)

Input: [1.  2.  3.  2.5]
Input array shape: (4,)
Weights: [[ 0.2   0.8  -0.5   1.  ]
 [ 0.5  -0.91  0.26 -0.5 ]
 [-0.26 -0.27  0.17  0.87]]
Weight array shape: (3, 4)
Output array before bias: [ 2.8   -1.79   1.885]
Output array before bias shape: (3,)
Biases: [2.  3.  0.5]
Biases array shape: (3,)
[4.8   1.21  2.385]


**Layer with multiple batch of inputs**

In [48]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# Numpy converts the list to np array internally
output = np.dot(inputs,np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


**Multiple Layers**

In [51]:
inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights1 = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases1 = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

weights3 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases3 = [-1, 2, -0.5]

weights4 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases4 = [-1, 2, -0.5]

output1 = np.dot(np.array(inputs), np.array(weights1).T) + np.array(biases1)
print(f'Output1: {output1}')
output2 = np.dot(np.array(output1), np.array(weights2).T) + np.array(biases2)
print(f'Output2: {output2}')
output3 = np.dot(np.array(output2), np.array(weights3).T) + np.array(biases3)
print(f'Output3: {output3}')
output4 = np.dot(np.array(output3), np.array(weights4).T) + np.array(biases4)
print(f'Output4: {output4}')

Output1: [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
Output2: [[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
Output3: [[-1.823206   2.2962155 -1.216877 ]
 [-3.474662   3.452205  -1.853103 ]
 [-1.4753446  2.7837363  1.0144873]]
Output4: [[-2.11222927  3.58871827  2.13664196]
 [-2.7573264   4.76311959  3.78986432]
 [-1.03001389  2.73693985  2.04939577]]
